sudo: false
notifications:
  email:
  - erik.m.bray@gmail.com
  on_failure: always
env:
  global:
  - secure: KrKvWPYAa7oCep884oQIJJA8ul+cwAGo/z6kKosdIMgZTE2h47zNeeByYg82cfrH57nhwEItrN5g55kKyN8wizZluJT5aflMItvHFGGPkMi7dr9sUHfcSagTQfazES8ZSxuvo1wtAm3J8Rq9q8BPUTqw1QHjMrKYoVk4d0NJgBg=
language: python
branches:
  only:
  - master
before_install:
- pip install -r requirements.txt
- git submodule update --init
install:
- fab build
script:
- fab travis_deploy
